export const CONFIG = {
  // Player
  PLAYER_SPEED: 10,
  PLAYER_SPRINT_MULTIPLIER: 1.5,
  PLAYER_MAX_HEALTH: 100,
  PLAYER_HEIGHT: 1.7,

  // Enemies
  ENEMY_BASE_HEALTH: 30,
  ENEMY_BASE_SPEED: 2,
  ENEMY_HEALTH_PER_WAVE: 5,
  ENEMY_SPEED_PER_WAVE: 0.3,
  ENEMY_DAMAGE: 10,
  ENEMY_ATTACK_RANGE: 1.5,
  ENEMY_ATTACK_COOLDOWN: 1.0,

  // Waves
  BASE_ENEMY_COUNT: 3,
  ENEMIES_PER_WAVE: 2,
  WAVE_BREAK_DURATION: 5,

  // Arena
  ARENA_SIZE: 60,
  WALL_HEIGHT: 5,

  // Weapons
  WEAPONS: [
    { name: 'Plasma Rifle', fireRate: 4, damage: 10, ammoMax: 30, spread: 0.02, rayCount: 1, color: 0x00ffff },
    { name: 'Laser Cannon', fireRate: 1, damage: 40, ammoMax: 10, spread: 0, rayCount: 1, color: 0xff00ff },
    { name: 'Spread Gun', fireRate: 2, damage: 5, ammoMax: 20, spread: 0.05, rayCount: 5, color: 0x00ff00 },
  ],

  // Visuals
  FOG_DENSITY: 0.015,
  FOG_COLOR: 0x000011,

  // Particles
  MAX_PARTICLES: 500,

  // Weapon Feel
  SWAY_IDLE_SPEED: 1.5,
  SWAY_IDLE_AMOUNT: 0.003,
  SWAY_MOVE_SPEED: 4,
  SWAY_MOVE_AMOUNT: 0.012,
  RECOIL_PITCH: -0.02,
  RECOIL_RECOVERY: 8,
  SPREAD_INCREASE_PER_SHOT: 0.003,
  SPREAD_MAX: 0.08,
  SPREAD_RECOVERY: 2,
  RELOAD_TIME: [1.5, 2.0, 1.8],
  RELOAD_DIP: 0.3,

  // Screen Shake
  SHAKE_DAMAGE_INTENSITY: 0.05,
  SHAKE_DAMAGE_DECAY: 5,
  SHAKE_SHOOT_INTENSITY: 0.015,
  SHAKE_SHOOT_DECAY: 10,

  // FOV
  FOV_NORMAL: 75,
  FOV_SPRINT: 80,
  FOV_LERP_SPEED: 6,

  // Beam Pool
  BEAM_POOL_SIZE: 20,

  // Audio
  SPATIAL_AUDIO_REF_DISTANCE: 1,
  SPATIAL_AUDIO_MAX_DISTANCE: 50,
  REVERB_DECAY: 2.0,
  AMBIENT_DRONE_FREQ: 55,
  AMBIENT_DRONE_GAIN: 0.04,

  // Enemy AI
  ENEMY_ALERT_RADIUS: 25,
  ENEMY_WANDER_RADIUS: 5,
  ENEMY_FLANK_CHANCE: 0.3,
  ENEMY_OBSTACLE_RAY_LENGTH: 3,
  ENEMY_FLINCH_STRENGTH: 2,
  ENEMY_KNOCKBACK_THRESHOLD: 30,
  ENEMY_KNOCKBACK_FORCE: 3,
  ENEMY_STAGGER_DURATION: 0.3,
  ENEMY_DEATH_TUMBLE_SPEED: 3,
};
